package com.agileict.shared.enums;

public enum AreaNegocioProfesional {
    TECNOLOGIA_IT,
    CIBERSEGURIDAD,
    DATA_ANALYTICS,
    INTELIGENCIA_ARTIFICIAL,
    INGENIERIA,
    TELECOMUNICACIONES,
    FINANZAS,
    LEGAL_COMPLIANCE,
    RECURSOS_HUMANOS,
    MARKETING_VENTAS,
    OPERACIONES,
    CONSULTORIA,
    PRODUCTO,
    SUPPLY_CHAIN_LOGISTICA,
    ENERGIA,
    SALUD_FARMA,
    RETAIL_ECOMMERCE,
    CONSTRUCCION_INFRAESTRUCTURA,
    SECTOR_PUBLICO
}